/**
 * Support Email API Route
 *
 * Handles support form submissions and sends emails via consolidated email service.
 * Sends support request to team and confirmation email to user.
 * Validates form data and provides appropriate error handling.
 *
 * Part of the consolidated email system under /api/email/
 */

import { NextRequest, NextResponse } from 'next/server';
import { supportFormSchema } from '@/features/support/schemas/support';
import { SupportConfirmationEmail } from '@/emails/support-confirmation';
import { SupportTeamNotificationEmail } from '@/emails/support-team-notification';
import { sendEmailWithComponent } from '@/features/email';
import { cleanupAfterEmailProcessing } from '@/utils/file-cleanup';

// Environment variables with fallbacks
const SUPPORT_EMAIL = process.env.SUPPORT_EMAIL || 'support@paymatch.app';
const FROM_EMAIL = process.env.RESEND_FROM_EMAIL || 'noreply@paymatch.app';
const FROM_NAME = process.env.RESEND_FROM_NAME || 'PayMatch';
const APP_URL = process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();

    // Validate the form data
    const validatedData = supportFormSchema.parse(body);

    // Prepare support team email content
    const supportEmailContent = `
New Support Request

Personal Information:
- Name: ${validatedData.name}
- Email: ${validatedData.email}
${validatedData.company ? `- Company: ${validatedData.company}` : ''}

Issue Details:
- Category: ${validatedData.category}
- Priority: ${validatedData.priority.toUpperCase()}
- Subject: ${validatedData.subject}

Message:
${validatedData.message}

${
  validatedData.attachments && validatedData.attachments.length > 0
    ? `
Attachments (${validatedData.attachments.length}):
${validatedData.attachments
  .map(
    (file, index) =>
      `${index + 1}. ${file.name} (${(file.size / 1024 / 1024).toFixed(2)} MB)`
  )
  .join('\n')}
`
    : ''
}

---
This message was sent via the PayMatch support form.
    `.trim();

    // Prepare email attachments
    const emailAttachments =
      validatedData.attachments?.map((file) => ({
        filename: file.name,
        content: file.url, // In a real implementation, this would be the actual file content
        contentId: file.name,
        contentType: file.type,
      })) || [];

    // Send support email to team using consolidated email service
    const supportEmailResult = await sendEmailWithComponent({
      to: SUPPORT_EMAIL,
      subject: `[${validatedData.priority.toUpperCase()}] ${validatedData.subject}`,
      from: `${FROM_NAME} Support <${FROM_EMAIL}>`,
      replyTo: validatedData.email,
      emailType: 'support',
      text: supportEmailContent,
      attachments: emailAttachments,
      component: SupportTeamNotificationEmail({
        userName: validatedData.name,
        userEmail: validatedData.email,
        userCompany: validatedData.company,
        category: validatedData.category,
        priority: validatedData.priority,
        subject: validatedData.subject,
        message: validatedData.message,
        attachments: validatedData.attachments || [],
      }),
    });

    if (!supportEmailResult.success) {
      console.error('Support email error:', supportEmailResult.error);
      return NextResponse.json(
        { error: 'Failed to send support email' },
        { status: 500 }
      );
    }

    // Send confirmation email to user using consolidated email service
    const confirmationEmailResult = await sendEmailWithComponent({
      to: validatedData.email,
      subject: `Support Request Received - ${validatedData.subject}`,
      from: `${FROM_NAME} <${FROM_EMAIL}>`,
      emailType: 'support',
      component: SupportConfirmationEmail({
        userName: validatedData.name,
        userEmail: validatedData.email,
        subject: validatedData.subject,
        category: validatedData.category,
        priority: validatedData.priority,
        supportEmail: SUPPORT_EMAIL,
        appUrl: APP_URL,
        // unsubscribeUrl will be automatically generated by the email service
      }),
    });

    if (!confirmationEmailResult.success) {
      console.error('Confirmation email error:', confirmationEmailResult.error);
      // Don't fail the request if confirmation email fails, just log it
      console.warn('Support request was sent but confirmation email failed');
    }

    // Clean up temporary files after successful email processing
    if (validatedData.attachments && validatedData.attachments.length > 0) {
      try {
        await cleanupAfterEmailProcessing(validatedData.attachments);
      } catch (cleanupError) {
        console.error('File cleanup error:', cleanupError);
        // Don't fail the request if cleanup fails, just log it
      }
    }

    return NextResponse.json(
      {
        success: true,
        messageId: supportEmailResult.messageId,
        confirmationSent: confirmationEmailResult.success,
        message: 'Support request sent successfully',
      },
      { status: 200 }
    );
  } catch (error) {
    console.error('Support API error:', error);

    if (error instanceof Error && error.name === 'ZodError') {
      return NextResponse.json(
        { error: 'Invalid form data', details: error.message },
        { status: 400 }
      );
    }

    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
