name: Supabase Backup

on:
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link to Supabase project
        run: |
          supabase link --project-ref ${{ secrets.PROJECT_ID }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}

      - name: Create backup directory
        run: mkdir -p supabase/backups

      - name: Backup database roles
        run: |
          supabase db dump --role-only -f supabase/backups/roles.sql

      - name: Backup database schema
        run: |
          supabase db dump --schema-only -f supabase/backups/schema.sql

      - name: Backup database data
        run: |
          supabase db dump --data-only -f supabase/backups/data.sql

      - name: Create timestamped backup
        run: |
          TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
          BACKUP_FILE="supabase/backups/backup_${TIMESTAMP}.sql"
          supabase db dump -f "$BACKUP_FILE"

          # Create latest symlink
          ln -sf "$(basename "$BACKUP_FILE")" supabase/backups/latest.sql

      - name: Commit backup files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'supabase backup'
          file_pattern: 'supabase/backups/*.sql'
          commit_user_name: 'Supabase Backup Bot'
          commit_user_email: 'backup@paymatch.ch'
