name: Supabase Deploy (main)

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: supabase-deploy-main
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link to Supabase project
        run: echo "$SUPABASE_DB_PASSWORD" | supabase link --project-ref "$PROJECT_ID"
        # Alternative: Use direct database URL instead of linking
        # run: supabase db push --db-url "$SUPABASE_DB_URL"

      - name: Push database migrations
        run: supabase db push
        # Add --include-seed if you want seed.sql to run in production

      - name: Push Supabase configuration
        run: supabase config push

      - name: Deploy all Edge Functions
        run: |
          if [ -d "supabase/functions" ] && [ "$(ls -A supabase/functions)" ]; then
            echo "Deploying Edge Functions..."
            supabase functions deploy
          else
            echo "No Edge Functions to deploy"
          fi
